name: Build Transformers + PyTorch CPU image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-tag: ["3.9-slim", "3.10-slim", "3.11-slim"]
        transformers-version: ["4.26"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: "${{ github.actor }}/python-transformers:${{ matrix.python-tag }}-${{ matrix.transformers-version }}-torch-cpu"
          build-args: |
            PYTHON_BASE_TAG=${{ matrix.python-tag }}
            TRANSFORMERS_VERSION===${{ matrix.transformers-version }}
          file: Dockerfile.torch-cpu
          context: .
